# Generated by Django 4.2.10 on 2024-02-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_single_cigar_price_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='state_of_product',
            field=models.ManyToManyField(to='products.stateofproduct'),
        ),
    ]
