# Generated by Django 4.2.10 on 2024-02-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_stateofproduct_product_state_of_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateofproduct',
            name='title2',
            field=models.CharField(blank=True, max_length=100, verbose_name='title for developer (dont change it)'),
        ),
    ]
